"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.4.
"""

from pathlib import Path
from datetime import timedelta
import os
from dotenv import load_dotenv
# ok
# Load environment variables from .env file
load_dotenv()

# Allowed Hosts (comma separated)
ALLOWED_HOSTS = ["*", "dominikbauer004.softvencealpha.com"]

CSRF_TRUSTED_ORIGINS = ["https://dominikbauer004.softvencealpha.com"]


# Build paths
BASE_DIR = Path(__file__).resolve().parent.parent

# Security
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG= True
# ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '').split(',')

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=2),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=6),
}

# Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
}

# Custom User
AUTH_USER_MODEL = 'User.CustomUser'


# settings.py

JAZZMIN_SETTINGS = {
    "site_title": "PUCEST Admin",
    "site_header": "PUCEST",
    "site_brand": "PUCEST Admin",
    "welcome_sign": "Welcome to PUCEST Admin Portal",
    "copyright": "PUCEST Ltd",
    
    # Top menu links for easy navigation
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {
            "name": "New Users", 
            "url": "admin:accounts_customuser_new",
            "permissions": ["accounts.view_customuser"],
            "icon": "fas fa-user-plus"
        },
        {
            "name": "Custom Users", 
            "url": "admin:accounts_customuser_custom", 
            "permissions": ["accounts.view_customuser"],
            "icon": "fas fa-users"
        },
        {
            "name": "All Users", 
            "url": "admin:accounts_customuser_changelist", 
            "permissions": ["accounts.view_customuser"],
            "icon": "fas fa-list"
        },
    ],
    
    # Custom sidebar menu
    "sidebar_menu": [
        {
            "name": "Dashboard",
            "url": "admin:index",
            "icon": "fas fa-tachometer-alt",
        },
        {
            "name": "User Management",
            "icon": "fas fa-users-cog",
            "models": [
                {
                    "name": "New Users", 
                    "url": "admin:accounts_customuser_new",
                    "icon": "fas fa-user-clock",
                    "badge": {
                        "text": "New",
                        "color": "warning"
                    }
                },
                {
                    "name": "Custom Users", 
                    "url": "admin:accounts_customuser_custom",
                    "icon": "fas fa-user-check",
                    "badge": {
                        "text": "Active", 
                        "color": "success"
                    }
                },
                {
                    "name": "All Users",
                    "url": "admin:accounts_customuser_changelist", 
                    "icon": "fas fa-list"
                },
            ]
        },
        {
            "name": "Authentication",
            "icon": "fas fa-lock",
            "models": [
                {
                    "name": "Groups",
                    "url": "admin:auth_group_changelist",
                    "icon": "fas fa-users",
                },
            ]
        },
    ],
    
    # Custom icons
    "icons": {
        "accounts.CustomUser": "fas fa-user",
        "auth.Group": "fas fa-users",
        "location.Location": "fas fa-map-marker-alt",
        "contacts.UserSelectedContact": "fas fa-address-book",
        "contacts.ContactAssignment": "fas fa-tasks",
        "contacts.Inquiry": "fas fa-question-circle",
        "token_blacklist.OutstandingToken": "fas fa-key",
        "token_blacklist.BlacklistedToken": "fas fa-ban",
    },
    
    # Show UI builder for additional customization
    "show_ui_builder": True,
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-success",
    "accent": "accent-primary",
    "navbar": "navbar-white navbar-light",
    "no_navbar_border": False,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
}


# Installed apps
INSTALLED_APPS = [
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    
    "corsheaders",

    'apps.User',
    'apps.Authentication',
    'apps.contacts',
    'apps.location',
    'apps.newsportal',
    'apps.inquiry',
]

# CSRF_TRUSTED_ORIGINS = [
#     "https://94732f8a593d.ngrok-free.app"
# ]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "https://94732f8a593d.ngrok-free.app",
# ]



# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    
    "corsheaders.middleware.CorsMiddleware",
    
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'project.urls'

# Templates
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'myproject',
#         'USER': 'myprojectuser',
#         'PASSWORD': 'password',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}



# Password validation
# AUTH_PASSWORD_VALIDATORS = [
#     {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
#     {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
#     {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
#     {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
# ]

AUTH_PASSWORD_VALIDATORS = []

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

JAZZMIN_SETTINGS = {
    "site_header": "PUCEST Admin",
    "site_title": "PUCEST Admin Portal",
     "site_logo": "images/logo.png",
     "welcome_sign": "Welcome to PUCEST Admin Portal",
}

# Static & Media
MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
os.path.join(BASE_DIR, 'static')
# Directory where collectstatic will collect static files
STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
